<a href="https://colab.research.google.com/github/Vinod826S/Process-Data-Analytics/blob/main/DC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import numpy
import cvxpy as cp

np.random.seed(42)

os.system('cls')

N = 6        # No of variables
samp = 100  # Total no of samples

A=numpy.zeros([N,N])

# Row1
A[0,0] = 14.47; A[0,1] = 4.8; A[0,4] = 3.9;
# Row2
A[1,0] = 4.8;A[1,1] = 8.47; A[1,2] = 1.75; A[1,3] = 6;
# Row3
A[2,1] = 1.75; A[2,2] = 10.47; A[2,5] = 3.4;
# Row4
A[3,1] = 6; A[3,3] = 11.47; A[3,4] = 3.8; A[3,5] = 1.9;
# Row5
A[4,0] = 3.9; A[4,3] = 3.8; A[4,4] = 7.45;
# Row6
A[5,2] = 3.4; A[5,3] = 1.9; A[5,5] = 12.42;

d, m1s = numpy.linalg.eig(A)

if (numpy.min(d) < 0):
    A = A + 1.1*abs(numpy.min(d)*numpy.identity(N))

A1 = numpy.linalg.inv(A)

# Data generation
D_data = numpy.random.multivariate_normal(numpy.zeros(N), A1, samp); # Data

S = numpy.cov(numpy.matrix.transpose(D_data))

X_i=numpy.diag(numpy.diag(A1))  # Initial guess
s_def = 17                        # Sparsity index
eit = 10                          # Max no of iterations


Theta = cp.Variable(shape = (N,N), PSD=True)
obj2 = cp.Maximize(cp.log_det(Theta) - cp.trace(Theta @ S) + alpha * cp.norm(Theta, 'fro'))
alpha = -0.1 #Regularization factor

prob = cp.Problem(obj2)
prob.solve()
if prob.status != cp.OPTIMAL:
    raise Exception('CVXPY Error')

In [ ]:
import numpy as np

rounded_values = np.round(Theta.value, 3)
rounded_values[rounded_values < 0.5] = 0 #Threshold = 0.5
print("Theta\n\n", rounded_values, "\n\n\nOriginal Theta\n\n", A)

Theta

 [[8.224 2.13  0.    0.    1.331 0.   ]
 [2.13  5.649 0.764 3.121 0.    0.   ]
 [0.    0.764 7.947 0.    0.    0.542]
 [0.    3.121 0.    6.494 1.655 0.517]
 [1.331 0.    0.    1.655 4.737 0.   ]
 [0.    0.    0.542 0.517 0.    7.578]] 


Original Theta

 [[14.47  4.8   0.    0.    3.9   0.  ]
 [ 4.8   8.47  1.75  6.    0.    0.  ]
 [ 0.    1.75 10.47  0.    0.    3.4 ]
 [ 0.    6.    0.   11.47  3.8   1.9 ]
 [ 3.9   0.    0.    3.8   7.45  0.  ]
 [ 0.    0.    3.4   1.9   0.   12.42]]
